name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test on Node.js ${{ matrix.node }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [12, 14]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - name: Test
        run: npm test
